site_name: pipelinellm
site_description: Batch-first Python workflows for LLM pipelines.
repo_name: conjuncts/pipelinellm
repo_url: https://github.com/conjuncts/pipelinellm
docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - .
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Philosophy: philosophy.md
  - Your first agent: agent_pattern.md
  - Quickstart: quickstart.md
  - Concepts:
    - Ask: ask.md
    - MessageState: msg_state.md
    - Persistence: persistence.md
    - Strategies: strategies.md
    - Memoize: memoize.md
  - Use cases:
    - Document processing: use_cases/document_processing.md
    - Chatbot: use_cases/multiple_conversations.md
    - RAG: use_cases/rag.md



extra_css:
  - stylesheets/extra.css